### ISSUE TITLE
Native implementation on Apple Devices (Core Graphics/Core Text)

### ISSUE THREAD

**Issue by MSleepyPanda** [MSleepyPanda/rust-font-loader#1]
Implement the API on Apple Device using the native APIs.

I don't own a mac and simply can't do it on my own. PRs welcome!

**Comment by onelson** [comment]
I'm looking into this. I'm new to rust, so I'll take it as far as I can and we'll see where we are ;)

**Comment by jrmuizel** [comment]
I have a WIP of this up at https://github.com/jrmuizel/rust-font-loader/tree/macos

**Comment by jrmuizel** [comment]
https://github.com/jrmuizel/rust-font-loader/tree/macos is now working. However, it needs https://github.com/servo/core-foundation-rs/pull/94 to land first. I'll talk to jdm about that tomorrow.

**Comment by MSleepyPanda** [comment]
Closed via https://github.com/MSleepyPanda/rust-font-loader/pull/4
